name: breez_liquid
description: Dart bindings for the Breez Liquid SDK
version: 0.1.0
homepage: https://breez.technology
repository: https://github.com/breez/breez-liquid-sdk

platforms:
  macos:
  linux:
  windows:
  android:
  ios:

environment:
  sdk: '>=3.0.0 <4.0.0'

dev_dependencies:
  build_runner: ^2.4.9
  ffigen: ">=8.0.0 <=11.0.0"
  freezed: ^2.5.2
  lints: ">=2.0.0 <4.0.0"
  path: ^1.9.0
  test: ^1.25.4
dependencies:
  ffi: ^2.1.2
  flutter_rust_bridge: 2.0.0-dev.33
  freezed_annotation: ^2.4.1
  meta: ^1.11.0
