name: breez_liquid
description: Dart bindings for the Breez Liquid SDK
version: 0.6.3
homepage: https://breez.technology
repository: https://github.com/breez/breez-sdk-liquid-dart
publish_to: 'none'

platforms:
  android:
  ios:
  macos:

environment:
  sdk: '>=3.4.0 <4.0.0'

dev_dependencies:
  build_runner: ^2.4.10
  ffigen: ">=8.0.0 <=11.0.0"
  freezed: ^2.5.3
  lints: ">=2.0.0 <=4.0.0"
  path: ^1.9.0
  test: ^1.25.5

dependencies:
  ffi: ^2.1.2
  flutter_rust_bridge: ">=2.4.0 <=2.7.0"
  freezed_annotation: ^2.4.1
  logging: ^1.2.0
  meta: ^1.12.0 # meta is pinned to version 1.12.0 by integration_test from the flutter SDK.
