name: breez_liquid
description: Dart bindings for the Breez Liquid SDK
version: 0.8.1
homepage: https://breez.technology
repository: https://github.com/breez/breez-sdk-liquid-dart
publish_to: 'none'

platforms:
  android:
  ios:
  macos:

environment:
  sdk: '>=3.7.0 <4.0.0' # ffi: 2.1.4 requires Dart 3.7.0 or greater 

dev_dependencies:
  build_runner: ^2.4.15
  ffigen: ^18.0.0
  freezed: ^3.0.4
  lints: ^5.1.1
  path: ^1.9.1
  test: ^1.25.15

dependencies:
  ffi: ^2.1.4
  flutter_rust_bridge: ">=2.4.0 <=2.9.0"
  freezed_annotation: ^3.0.0
  logging: ^1.3.0
  meta: ^1.16.0
