name: flutter_breez_liquid_example
description: Demonstrates how to use the flutter_breez_liquid plugin.
publish_to: 'none'
version: 0.2.2-dev14

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_rust_bridge: 2.2.0
  flutter_breez_liquid:
    git:
      url: https://github.com/breez/breez-sdk-liquid-flutter
  # When depending on this package from a real application you should use:
  #   flutter_breez_liquid: ^x.y.z
  # See https://dart.dev/tools/pub/dependencies#version-constraints
  # The example app is bundled with the plugin so we use a path dependency on
  # the parent directory to use the current plugin's version.
  # path: ../
  bip39: ^1.0.6
  flutter_secure_storage: ^9.2.2
  mobile_scanner: ^5.1.1
  path_provider: ^2.1.3
  qr_flutter: ^4.1.0
  intl: ^0.19.0
  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/icons/